### ISSUE TITLE
Does not compile. Missing pom dependencies.

### ISSUE THREAD

**Issue by adrian-francisco** [jay1da/playground#1]
The master does not compile.  It is missing dependencies in the pom.

**Comment by jay1da** [comment]
Resolved.  Please test and confirm.

**Comment by adrian-francisco** [comment]
Still broken:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.
1:compile (default-compile) on project Playground: Compilation failure: Compilat
ion failure:
[ERROR] /home/adrian/git/jay1da-playground/src/playground/Playground.java:[8,31]
 package org.apache.commons.lang does not exist
[ERROR] /home/adrian/git/jay1da-playground/src/playground/Playground.java:[9,31]
 package org.apache.commons.lang does not exist
[ERROR] /home/adrian/git/jay1da-playground/src/playground/Playground.java:[40,28
] cannot find symbol
[ERROR] symbol:   variable StringEscapeUtils
[ERROR] location: class playground.Playground
[ERROR] /home/adrian/git/jay1da-playground/src/playground/Playground.java:[60,16
] cannot find symbol
[ERROR] symbol:   variable StringUtils
[ERROR] location: class playground.Playground
[ERROR] /home/adrian/git/jay1da-playground/src/playground/Playground.java:[61,16
] cannot find symbol
[ERROR] symbol:   variable StringUtils
[ERROR] location: class playground.Playground

**Comment by jay1da** [comment]
Try again.

**Comment by adrian-francisco** [comment]
Confirmed. Great job!
